spring.application.name=payment-service
server.port=8084

client.order-service.url=http://order.local:8083

management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents,retries,retryevents,ratelimiters,ratelimiterevents,timelimiters,timelimiterevents
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.instances.orderClient.register-health-indicator=true
resilience4j.circuitbreaker.instances.orderClient.sliding-window-size=5
resilience4j.circuitbreaker.instances.orderClient.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.orderClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.orderClient.wait-duration-in-open-state=10s

resilience4j.retry.instances.orderClient.max-attempts=3
resilience4j.retry.instances.orderClient.wait-duration=300ms

resilience4j.ratelimiter.instances.orderClient.limit-for-period=10
resilience4j.ratelimiter.instances.orderClient.limit-refresh-period=1s
resilience4j.ratelimiter.instances.orderClient.timeout-duration=0

resilience4j.timelimiter.instances.orderClient.timeout-duration=2s
resilience4j.timelimiter.instances.orderClient.cancel-running-future=true
