spring.application.name=order-service
server.port=8083

client.user-service.url=http://user.local:8081
client.food-service.url=http://food.local:8082

management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents,retries,retryevents,ratelimiters,ratelimiterevents,timelimiters,timelimiterevents
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.instances.userClient.register-health-indicator=true
resilience4j.circuitbreaker.instances.userClient.sliding-window-size=5
resilience4j.circuitbreaker.instances.userClient.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.userClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userClient.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.foodClient.register-health-indicator=true
resilience4j.circuitbreaker.instances.foodClient.sliding-window-size=5
resilience4j.circuitbreaker.instances.foodClient.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.foodClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.foodClient.wait-duration-in-open-state=10s

resilience4j.retry.instances.userClient.max-attempts=3
resilience4j.retry.instances.userClient.wait-duration=300ms
resilience4j.retry.instances.foodClient.max-attempts=3
resilience4j.retry.instances.foodClient.wait-duration=300ms

resilience4j.ratelimiter.instances.userClient.limit-for-period=10
resilience4j.ratelimiter.instances.userClient.limit-refresh-period=1s
resilience4j.ratelimiter.instances.userClient.timeout-duration=0
resilience4j.ratelimiter.instances.foodClient.limit-for-period=10
resilience4j.ratelimiter.instances.foodClient.limit-refresh-period=1s
resilience4j.ratelimiter.instances.foodClient.timeout-duration=0

resilience4j.timelimiter.instances.userClient.timeout-duration=2s
resilience4j.timelimiter.instances.userClient.cancel-running-future=true
resilience4j.timelimiter.instances.foodClient.timeout-duration=2s
resilience4j.timelimiter.instances.foodClient.cancel-running-future=true
